Deploy hazırlığı

diff --git a/Dockerfile.web b/Dockerfile.web
--- a/Dockerfile.web
+++ b/Dockerfile.web
@@ -9,8 +9,6 @@ ENV TZ=Europe/Istanbul
 RUN apt-get update && apt-get install -y tzdata \
     && ln -snf /usr/share/zoneinfo/$TZ /etc/localtime \
     && echo $TZ > /etc/timezone \
-    && apt-get install -y gcc libpq-dev \
-    && apt-get clean \
     && rm -rf /var/lib/apt/lists/*
 
 # Bağımlılıkları yükle
@@ -20,16 +18,12 @@ RUN --mount=type=cache,target=/root/.cache/pip pip install --upgrade pip && pip 
 # Proje dosyalarını kopyala
 COPY . .
 
-# Statik dosyaları toplayın
-RUN python manage.py collectstatic --noinput --settings=core.settings.prod
-
 # Kullanıcı oluştur ve geçiş yap
 RUN useradd -m myuser
 USER myuser
 
 # Ortam değişkenlerini ayarla
 ENV DJANGO_SETTINGS_MODULE=core.settings.prod
-ENV PORT=10000
 
 # Gunicorn ile uygulamayı başlat
-CMD ["gunicorn", "--bind", "0.0.0.0:10000", "core.wsgi:application", "--workers", "4", "--timeout", "120"]
+CMD ["sh", "-c", "gunicorn --bind 0.0.0.0:$PORT core.wsgi:application || echo 'Gunicorn failed to start with exit code: $?' && sleep infinity"]
